services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_collab_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    command: sh -c "mix ecto.setup && mix phx.server"
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/task_collab_dev"
      DATABASE_HOST: "db"
      MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data:
